backend:
  name: github
  repo: literaturnirazgovori/literaturnirazgovori.github.io # Path to your Github repository
  branch: work # Branch to update
  base_url: https://warm-woodland-78106.herokuapp.com

# publish_mode: editorial_workflow
media_folder: Uploads
public_folder: Uploads

collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Hidden", name: "hidden", widget: "boolean", default: true }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - label: "Author"
        name: "author"
        widget: "select"
        default: "Antonia"
        options:
          - { label: "Антония", value: "Antonia" }
          - { label: "Гост-автор", value: "Guest" }
      - label: "Featured Image"
        name: "image"
        widget: "image"
        media_library:
          config:
            multiple: true
      - { label: "Body", name: "body", widget: "markdown" }
      # - { label: "Body", name: "body", widget: "string" }
      - label: "Category"
        name: "category"
        widget: "select"
        default: "interviews"
        options:
          - { label: "Разговори", value: "talks" }
          # - { label: "Разговори", value: "interviews" }
          - { label: "Рецензии", value: "bookreviews" }
          - { label: "Интервюта", value: "interviews" }
          - { label: "Преводна поезия", value: "translations" }
          - { label: "Нови книги", value: "newbooks" }
          - { label: "Новини и събития", value: "newsevents" }
      - {label: "Tags", name: "tags", widget: "list"}   
      - label: "Schedule publish at"
        name: "schedule"
        widget: "datetime"
        default: ""
        format: "YYYY-MM-DD HH:mm"
        dateFormat: "YYYY-MM-DD"
        timeFormat: "HH:mm"
